# Este archivo mods.toml contiene la información de configuración para la carga de mods en Forge.
# Encuentra más detalles sobre el formato TOML en: https://github.com/toml-lang/toml

modLoader="javafml" # Cargador de mod, obligatorio.
loaderVersion="[38,)" # Versión de Forge mínima requerida, obligatorio.
license="All rights reserved" # Licencia del mod, obligatorio.
#issueTrackerURL="https://example.com/issues" # URL opcional para reporte de errores.

[[mods]] # Sección obligatoria que describe el mod.
modId="empowered_armaments" # Identificador único del mod, obligatorio.
version="0.0.2-1.18-38.0.17" # Versión del mod, obligatorio.
displayName="Empowered Armaments" # Nombre que se mostrará para el mod, obligatorio.
credits="Inspirado en la comunidad de modding de Minecraft y desarrollado por Belion Dev" # Créditos opcionales.
authors="Belion Dev" # Autor o autores del mod, opcional.
logoFile="empowered_armaments.png"

# Descripción detallada del mod (obligatoria).
description = '''
Empowered Armaments is a mod designed to enhance the gameplay experience with basic Minecraft weapons, such as swords and axes. This mod allows players to upgrade and improve vanilla weapons, adding a new level of power and functionality to make them more effective in combat. With Empowered Armaments, players can explore new crafting recipes and use advanced materials to enhance their weapons, increasing their damage and speed stats. It is an ideal add-on for those looking to take their adventures to the next level while maintaining the classic Minecraft style.
'''


[[dependencies.empowered_armaments]] # Dependencia de Forge, obligatoria.
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="BOTH"

[[dependencies.empowered_armaments]] # Dependencia de Minecraft, obligatoria.
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
